sploodl/expenses/urls.py
from django.conf.urls import url

from . import views

app_name = 'expenses'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^view/(?P<uuid>[-a-zA-z0-9]+)/$', views.listView, name='list'),
    url(r'^balances/(?P<uuid>[-a-zA-z0-9]+)/$', views.balanceView, name='balances'),
    url(r'^delete/(?P<uuid>[-a-zA-z0-9]+)/(?P<id>[0-9]+)/$', views.delete, name='delete'),
    url(r'^create/$', views.createView, name='create'),
]

sploodl/sploodl/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^expenses/', include('expenses.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^tags_input/', include('tags_input.urls', namespace='tags_input')),
]

sploodl/expenses/models.py
from __future__ import unicode_literals
import uuid
from django.db import models
from django.utils import timezone
from django.db.models.signals import post_save, pre_delete

from .currency.converter import convertValue, CURRENCIES

#CURRENCIES = [('GBP', 'British Pound Sterling'),
#                ('USD', 'United States Dollar'),
#                ('EUR', 'Euro'),
#                ('DKK', 'Danish Krone'),
#                ('SEK', 'Swedish Krona')]


class Sploodl(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=140)
    home_currency = models.CharField(max_length=3, choices = CURRENCIES)

    def __str__(self):
        return self.name


class Participant(models.Model):
    sploodl = models.ForeignKey(Sploodl, on_delete=models.CASCADE)
    name = models.CharField(max_length=70)

    def __str__(self):
        return self.name

    def balance(self):
        return sum([iou.value for iou in self.iou_set.all()])


class Transaction(models.Model):
    sploodl = models.ForeignKey(Sploodl, on_delete=models.CASCADE)
    dateCreated = models.DateTimeField(default = timezone.now)
    dateModified = models.DateTimeField(default=timezone.now)
    description = models.CharField(max_length=140)
    currency = models.CharField(max_length=3, choices = CURRENCIES)
    people_by = models.ManyToManyField(Participant,related_name='+')
    people_for = models.ManyToManyField(Participant,related_name='+')
    value = models.DecimalField(max_digits=12, decimal_places=2)

    def __str__(self):
        return self.description

    def refreshIOUs(self):
        #Delete IOUs
        self.deleteIOUs()

        # Create IOUs
        self.createIOUs()

        #Update date modified
        self.dateModified = timezone.now()


    def deleteIOUs(self):
        #Delete IOUs
        for iou in self.iou_set.all():
            iou.delete()


    def createIOUs(self):
        #Currency conversion
        self.valueInHomeCurrency = convertValue(float(self.value),
                                            self.currency, self.sploodl.home_currency)

        # Credit
        by_query_set = self.people_by.get_queryset()
        divisor = len(by_query_set)
        for participant in by_query_set:
            i=IOU(sploodl = self.sploodl, participant = participant, transaction = self,
                value = self.valueInHomeCurrency/divisor)
            i.save()

        # Debit
        for_query_set = self.people_for.get_queryset()
        divisor = len(for_query_set)
        for participant in for_query_set:
            i= IOU(sploodl = self.sploodl, participant = participant, transaction = self,
                value = -1*self.valueInHomeCurrency/divisor)
            i.save()


def model_created_or_updated(sender, **kwargs):
    the_instance = kwargs['instance']
    the_instance.refreshIOUs()

post_save.connect(model_created_or_updated, sender=Transaction)

def model_deleted(sender, **kwargs):
    the_instance = kwargs['instance']
    the_instance.deleteIOUs()

pre_delete.connect(model_deleted, sender=Transaction)


class IOU(models.Model):
    sploodl = models.ForeignKey(Sploodl, on_delete=models.CASCADE)
    participant = models.ForeignKey(Participant, on_delete=models.CASCADE)
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    value = models.DecimalField(max_digits=12, decimal_places=2)

    def __str__(self):
        return self.participant.name + " " + str(self.value)

sploodl/expenses/forms.py
from django import forms
from expenses.models import *
from .currency.converter import CURRENCIES


class SploodlForm(forms.Form):
    name = forms.CharField(label='Title', max_length=140)
    homeCurrency = forms.ChoiceField(choices = CURRENCIES, label="Home currency")
    participants = forms.CharField(label = 'Participants names (comma separated)')


class TransactionForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        sploodl = kwargs.pop('sploodl')
        super(TransactionForm, self).__init__(*args, **kwargs)
        # snip the other fields for the sake of brevity
        # Adding content to the form
        self.fields['people_by'].queryset = sploodl.participant_set.all()
        self.fields['people_for'].queryset = sploodl.participant_set.all()
        self.fields['people_for'].initial = sploodl.participant_set.all()

    class Meta:
        model = Transaction
        fields = ['description', 'currency', 'value', 'people_by', 'people_for']

sploodl/expenses/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse


from .models import *
from .forms import *


def index(request):
    return HttpResponse("Hello, world. You're at the Sploodl index.")

def listView(request, uuid):
    sploodl = get_object_or_404(Sploodl, id=uuid)
    latest_transaction_list = sploodl.transaction_set.order_by('-dateCreated')[:20]
    if request.method == 'POST':
        form = TransactionForm(request.POST, sploodl=sploodl, auto_id=False)
        if form.is_valid():
            new_transaction = form.save(commit=False)
            new_transaction.sploodl = sploodl
            new_transaction.dateCreated = timezone.now()
            new_transaction.dateModified = timezone.now()
            new_transaction.save()
            form.save_m2m()
            new_transaction.createIOUs()

        return HttpResponseRedirect(reverse('expenses:list', args = (sploodl.id,)))
    else:
        add_another = TransactionForm(sploodl=sploodl, auto_id=False)
        return render(request, 'expenses/list.html', {'sploodl': sploodl,
                                                      'add_form': add_another,
                                                      'latest_transaction_list': latest_transaction_list})


def balanceView(request, uuid):
    sploodl = get_object_or_404(Sploodl, id=uuid)
    return render(request, 'expenses/balances.html', {'sploodl': sploodl})


def delete(request, uuid, id):
    sploodl = get_object_or_404(Sploodl, id=uuid)
    get_object_or_404(Transaction, id = id).delete()
    return HttpResponseRedirect(reverse('expenses:list', args = (sploodl.id,)))


def createView(request):
    # if this is a POST request we need to process the form data
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = SploodlForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # Create the Sploodl instance
            name = form.cleaned_data['name']
            homeCurrency = form.cleaned_data['homeCurrency']
            participants = form.cleaned_data['participants']
            parti_list = [parti.strip() for parti in participants.split(",")]

            newSploodl = Sploodl(name=name, home_currency = homeCurrency)
            newSploodl.save()

            for parti in parti_list:
                new_participant = Participant(name = parti, sploodl = newSploodl)
                new_participant.save()


            return HttpResponseRedirect(reverse('expenses:list', args = (newSploodl.id,)))

    # if a GET (or any other method) we'll create a blank form
    else:
        form = SploodlForm()

    return render(request, 'expenses/create.html', {'spl_form': form})

sploodl/expenses/templates/expenses/balances.html
<h1>{{ sploodl.name }}</h1>
<h2><a href = "{% url 'expenses:list' sploodl.id %}">Transactions</a> | Balances</h2>


<table>
{% for participant in sploodl.participant_set.all %}
    <tr>
        <td>{{ participant.name }}</td>
        <td>{{ participant.balance }}</td>
    </tr>
{% endfor %}
</table>

sploodl/expenses/templates/expenses/create.html
<body>
    <h1>Manage expenses</h1>
    <h2>Create a Sploodl</h2>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <form action="" method="post">
        {% csrf_token %}
        {{ spl_form }}
        <input type="submit" value="Submit" />
    </form>
</body>

sploodl/expenses/templates/expenses/list.html
<h1>{{ sploodl.name }}</h1>
<h2>Transactions | <a href = "{% url 'expenses:balances' sploodl.id %}">Balances</a></h2>



<table>
    <thead>
    <tr>
        <th>Description</th>
        <th>Currency</th>
        <th>Amount</th>
        <th>By</th>
        <th>For</th>
        <th>Date created</th>
        <th>Date last modified</th>
        <th>&nbsp;</th>
        <th>&nbsp;</th>
    </tr>
    </thead>
    <tbody>
    {% for transaction in latest_transaction_list %}
    <tr>
        <td>{{ transaction.description }}</td>
        <td>{{ transaction.currency }}</td>
        <td>{{ transaction.value }}</td>
        <td>
            {% for person in transaction.people_by.get_queryset %}
                {{ person.name }}
            {% endfor %}
        </td>
        <td>
            {% for person in transaction.people_for.get_queryset %}
                {{ person.name }}
            {% endfor %}
        </td>
        <td>{{ transaction.dateCreated }}</td>
        <td>{{ transaction.dateModified }}</td>
        <td>Edit</td>
        <td><a href="{% url 'expenses:delete' sploodl.id transaction.id %}">Delete</a></td>
    </tr>
    {% endfor %}
    <tr><form action="" method="post">
    {% csrf_token %}
    {{ add_form.no_field_errors }}
        <td>
            {{ add_form.description.errors }}
            {{ add_form.description }}
        </td>
        <td>
            {{ add_form.currency.errors }}
            {{ add_form.currency }}
        </td>
        <td>
            {{ add_form.value.errors }}
            {{ add_form.value }}
        </td>
        <td>
            {{ add_form.people_by.errors }}
            {{ add_form.people_by }}
        </td>
        <td>
            {{ add_form.people_for.errors }}
            {{ add_form.people_for }}
        </td>
        <td><input type="submit" value="Save" /></td>
        <td></td>
        <td></td>
        <td></td>
    </form></tr>
    </tbody>
</table>